### ISSUE TITLE
namespace exists in mysql database but the namespace_exists function returns not found

### ISSUE THREAD

**Issue by hadishahpuri** [nikashitsa/ger_mysql_esm#2]
hi. I was using the hapiGER for my project and I faced a 404 error in namespace checking so I followed the code and found the bug so I'm sending a pull request. hope you check it out.

**Comment by nikashitsa** [comment]
Hi, what mysql database version do you use?

**Comment by hadishahpuri** [comment]
8

**Comment by nikashitsa** [comment]
Thanks for your report!
